version: '3'

services:
  zookeeper:
    image: 'zookeeper'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/data'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      my-network:
        aliases:
          - zookeeper
  kafka:
    image: 'kafka'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/data'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_SOCKET_REQUEST_MAX_BYTES=200000000
    depends_on:
      - zookeeper
    networks:
      my-network:
        aliases:
          - kafka
  kafdrop:
    image: 'kafdrop'
    ports:
      - '9000:9000'
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
      - JVM_OPTS=-Xms32M -Xmx64M
      - SERVER_SERVLET_CONTEXTPATH=/
    depends_on:
      - zookeeper
      - kafka
    networks:
      my-network:
        aliases:
          - kafdrop
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
    my-network:
        driver: bridge