version: '3'
services:
  rabbitmq:
    image: "rabbitmq-mng"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      my-network:
        aliases:
          - rabbitmq
networks:
    my-network:
        driver: bridge