version: '3'
services:
  catalog-service:
    image: "catalog-service-1"
    environment:
      - HOST_NAME=catalog-service
      - kafka.topic=center-log-topic
      - kafka.server=kafka:9200
      - CATALOGDATA_HOST=http://catalog-data:8000
    ports:
      - "8100:8100"
    depends_on:
      - "kafka"
    networks:
      my-network:
        aliases:
          - catalog-service
  zookeeper:
    image: 'zookeeper'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/data'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      my-network:
        aliases:
          - zookeeper
  kafka:
    image: 'kafka'
    ports:
      - '9092:9092'
      - '29092:29092'
    volumes:
      - 'kafka_data:/data'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_SOCKET_REQUEST_MAX_BYTES=200000000
    depends_on:
      - zookeeper
    networks:
      my-network:
        aliases:
          - kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
    my-network:
        driver: bridge